services:
  # Order Microservice
  order_db:
    image: postgres:13
    container_name: order_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AURA_MS_ORDER
    ports:
      - "5432:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    networks:
      - aura_network

  order_flyway:
    image: flyway/flyway:10.12.0
    container_name: order_flyway
    depends_on:
      - order_db
    command: [
      "migrate",
      "-url=jdbc:postgresql://order_db:5432/AURA_MS_ORDER",
      "-user=postgres",
      "-password=postgres"
    ]
    volumes:
      - ./aura-ms-order/src/main/resources/db/migration:/flyway/sql
    networks:
      - aura_network

networks:
  aura_network:
    driver: bridge

volumes:
  order_pgdata: