services:
  # Order Microservice
  order_db:
    image: postgres:13
    container_name: order_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AURA_MS_ORDER
    ports:
      - "5432:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    networks:
      - aura_network

  order_flyway:
    image: flyway/flyway:10.12.0
    container_name: order_flyway
    depends_on:
      - order_db
    command: [
      "migrate",
      "-url=jdbc:postgresql://order_db:5432/AURA_MS_ORDER",
      "-user=postgres",
      "-password=postgres"
    ]
    volumes:
      - ./aura-ms-order/src/main/resources/db/migration:/flyway/sql
    networks:
      - aura_network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-consumer
    ports:
      - "4567:4566" # Porta para acessar os serviços da AWS
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
    networks:
      - aura_network
  init-sqs-consumer:
    image: amazon/aws-cli:latest
    container_name: init-sqs
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10
        aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name new-order-queue
        aws --endpoint-url=http://localstack:4566 sqs list-queues
      "
    networks:
      - aura_network

networks:
  aura_network:
    driver: bridge

volumes:
  order_pgdata: