CREATE TABLE MS_ORDER
(
    ID BIGSERIAL PRIMARY KEY,
    CLIENT_ID BIGSERIAL NOT NULL,
    ITEMS VARCHAR(255) NOT NULL,
    DT_CREATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_ID BIGSERIAL NOT NULL
);
